account/urls.py
from django.conf.urls import url
from . import views

app_name ='account'

urlpatterns =[
    #url(r'^selection/$',views.selection_view,name="selection"),
    url(r'^signup/$',views.signup_view,name="signup"),
    url(r'^login/$',views.login_view,name='login'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^profile/(?P<user>[\w-]+)/$',views.profile_view,name="profile"),
    url(r'^profile_edit/',views.profile_edit_view,name="profile_edit"),
    url(r'profile_view/(?P<user>[\w-]+)/$',views.profile_search_result,name="profile_view")

]

articles/urls.py
from django.conf.urls import url
from . import views

app_name="articles"

urlpatterns = [
    url(r'^$',views.article_list,name="list"),
    url(r'^create/$',views.article_create,name="create"),
    url(r'^(?P<slug>[\w-]+)/$',views.article_details,name="details"),
    
]

blog/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

app_name="blog"

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/',include('account.urls')),
    url(r'^articles/',include('articles.urls')),
    url(r'^about/$',views.about,name="about"),
    url(r'^contact/$',views.contact,name="contact"),
    url(r'^$',article_views.article_list,name="home"),
    url(r'^search/$',views.search_view,name="search"),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from cloudinary.models import CloudinaryField


class Profile(models.Model):
    email = models.CharField(max_length=200, default="no e-mail...")
    bio = models.TextField(default='no bio')
    created = models.DateTimeField(auto_now_add=True)
    avatar = CloudinaryField('avatar')
    created = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    profile_name=models.CharField(max_length=100,default="no_name",blank=True)
    last_update = models.DateTimeField(null=True,blank= True)
    artilce_num = models.IntegerField(default=0)

    

    def __str__(self): 
        return f"{self.user}"

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = CloudinaryField('thumb')
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)

    
    
    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."
    
    

account/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
from . import form as fm
from .models import Profile
from django.contrib.auth.decorators import login_required
from articles.models import Article

def selection_view(request):
    return render(request,"account/selection.html")

@login_required(login_url="/account/selection/")
def profile_view(request,user):
    profile=Profile.objects.get(user=request.user)
    articles = Article.objects.all().filter(author=profile.user)
    return render(request,'account/profile.html',{'profile':profile,'articles':articles})

def profile_search_result(request,user):
    if request.method == "GET":
        search = request.GET.get('result')
        print(search)
        profile = Profile.objects.get(profile_name=search)
        return render(request,'account/profile_search_result.html',{'profile':profile})

@login_required(login_url="/account/selection/")
def profile_edit_view(request):
    if request.method == 'POST':
        instance = Profile.objects.get(user=request.user)
        forms = fm.CreateAccount(request.POST,request.FILES,instance=instance)
        if forms.is_valid():
            forms.save()
            return redirect("account:profile",request.user)
    else:
        form = fm.CreateAccount()
        return render(request,"account/profile_edit.html",{'form':form})

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user =form.save()
            login(request,user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()
        return render(request,"account/signup.html",{'form':form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')

    else:
        form = AuthenticationForm()
    return render(request,'account/login.html',{'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

articles/views.py
from django.shortcuts import render,redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import form
import time
from account.models import Profile


def article_list(request):
    articles = Article.objects.all().order_by('date')

    return render(request,'articles/article_list.html',{'articles':articles})


def article_details(request,slug):
    #return HttpResponse(slug)

    article =Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})


@login_required(login_url="/account/selection/")
def article_create(request):
    if request.method == 'POST':
        forms = form.CreateArticle(request.POST,request.FILES)
        if forms.is_valid():
            instance = forms.save(commit=False)
            instance.author = request.user
            instance.save()
            update = Profile.objects.get(user=instance.author)
            last = instance.date - update.last_update
            
            if last.total_seconds() <= 300:
                update.artilce_num = update.artilce_num + 1
                if update.artilce_num == 3:
                    print("stfp")
                    update.artilce_num = 0
                    return render(request,"articles/warning.html")

            else:
                update.artilce_num = 0    
                
            return redirect("articles:list")
    else:
        forms = form.CreateArticle()
        return render(request,"articles/article_create.html",{'form':forms})

blog/views.py
from django.http import HttpResponse
from django.shortcuts import render
from account.models import Profile

def home(request):
    #return HttpResponse("Home")
    return render(request,"homepage.html")

def about(request):
    #return HttpResponse("about")
    return render(request,"about.html")

def contact(request):
    return render(request,"contact.html")

def search_view(request):
    if request.method == "GET":
        search = request.GET.get('search')
        post = Profile.objects.all().filter(profile_name=search)
        return render(request,'search.html',{'post':post})

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="class-article">
    <h2 class="h2-create">Create an awesome new article</h2>
    <form class="site-form" action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form}}
        
        <input type="submit" value="Create">
    </form>
</div>
{% endblock %} 

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="article-details">
    <div class="article">
        <center>><img class="article-detail-img" src="{{ article.thumb.url }}"/></center>
        <h1>{{ article.title }}</h1>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
        <p>{{ article.author }}</p>
    </div>
</div>

{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}


{% block content %}

        <h1 class="h1-article_list">Article List</h1>
        <div class="articles">
            {% for article in articles %}
            <a href="{% url 'articles:details' article.slug %}"><div class="article">
                    
                    <h2>{{article.title}}</h2>
                    <p> {{article.snippet}}</p>
                    <p>{{article.date}}</p>
                    <p class="author">added by {{article.author.username}}</p>
                </div></a>
            {% endfor %}

        </div>

{% endblock %}

articles/templates/articles/warning.html
{% extends 'base_layout.html' %}


{% block content %}
<h1>You were created too many article slow down man :(</h1>

{% endblock %}

templates/about.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
<div class="about">
    <img class="photo" src="{% static 'my_photo.jpg' %}" alt="My photo">
    <p class="who_am_i">
        Hi my name is Ata Özdamar. I am a second year computer engineering student at Middle East Technical University. I made this blog just for fun. So probobly there are tons of error. Feels safe while using the site. I made this blog with python Django. 
    </p>
</div>
{% endblock %}

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Articles</title>
        <link rel ="stylesheet" href= "{% static 'style.css' %}">
        <link rel="shortcut icon" href="{%  static 'favicon.ico' %}">
    </head>
    <body>
        <div style="background-image: url('/static/Starsinthesky.jpg');"></div>
        <header class="wrapper">
            <ul class="nav-bar">
                <li class="nav"><a href="{% url 'home' %}">Home</a></li>
                {% if user.is_authenticated %} 
                    <li class="nav"><a href="{% url 'account:profile' request.user %}">Your profile</a></li>
                {% endif %}
                <li class="nav"><a href="{% url 'about' %}">About</a></li>
                <li class="nav"><a href="{% url 'contact' %}">Contact</a></li>

            </ul>
            <h1><a href="{% url 'home' %}"><img class="back" src="{% static 'experyshare_logo.png' %}" alt="blog"/></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                   <li>
                       <form class="logout-link" action="{% url 'account:logout' %}" method='post'>
                           {% csrf_token %}
                           <button type="submit" class="highlight">Logout</button>
                       </form>
                   </li> 
                   <li>
                       <a href="{% url 'articles:create' %}" class="highlight" >Create article</a>
                   </li>
                   {% else %}
                        <li><a href="{% url 'account:login' %}" class="highlight">Login</a></li>
                        <li><a href="{% url 'account:signup' %}" class="highlight">Signup</a></li>
                   {% endif %}
                </ul>
            </nav>
        </header>
        <div class="search">
            <form class="search-form" action="{% url 'search' %}" method='get'>
                 <input class="search-input" type="text" placeholder="Search" name="search"/>
                 <button class="search-button" type="submit"><i class="fa fa-search"></i>Search</button>
                 
             </form>
         </div>
        <div class ="wrapper">
            {% block content %}
            {% endblock %}
        </div>
        <style>
        #myBtn {
            display: none;
            position: fixed;
            bottom: 20px;
            right: 30px;
            z-index: 99;
            font-size: 18px;
            border: none;
            outline: none;
            background-color:#00dba0;
            color: white;
            cursor: pointer;
            padding: 15px;
            border-radius: 4px;
          }
          
          #myBtn:hover {
            background-color: #555;
          }
          </style>
          <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
          <script>
          
          var mybutton = document.getElementById("myBtn");
          
          
          window.onscroll = function() {scrollFunction()};
          
          function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
              mybutton.style.display = "block";
            } else {
              mybutton.style.display = "none";
            }
          }
          
          
          function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
          }
          </script>
    </body>
</html>

templates/contact.html
{% extends 'base_layout.html' %}
{% load static %}
{% block content %}
<p class="github-link"><img class="github-logo" src="{% static 'github_logo.png' %}" alt="github-logo" />GitHub:<a href="https://github.com/Lynextion"> https://github.com/Lynextion</a></p>
<p class="email"><img class="mail-logo" src="{% static 'mail-logo.jpg' %}" alt="email-logo" />Email: <ataozdamar@gmail class="com">ataozdamar@gmail.com</ataozs>
<p class="linkedin-link"><img class="linkedin-logo" src="{% static 'linkedin-logo.png' %}" alt="linkedin-logo" />Linkedin:<a href="https://www.linkedin.com/in/ata-özdamar-7704aa1b1/"> https://www.linkedin.com/in/ata-özdamar-7704aa1b1/</a></p>
{% endblock %}

templates/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Homepage</title>
    </head>
    <body>
        <h1>This is a Homepage btw</h2>
    </body>
</html>

templates/search.html
{% extends 'base_layout.html' %}

{% block content %}

{% for searchs in post %}
<div class="search-results">
    <form class="results" action="{% url 'account:profile_view' searchs.user  %}" method='get' >
        <button class="search-result" type="submit" name="result" value="{{ searchs.user }}"><h1>{{ searchs.user }}</h1>
    </form>
</div>
{% endfor %}
{% endblock %}